### ISSUE TITLE
Request: HTTPS

### ISSUE THREAD

**Issue by ghost** [ingenology/mars_weather_api#5]
Hello,

If it is not too much trouble, I'd like to request that the MAAS API implement HTTPS so there are no "Mixed Content" issues or errors when accessing the MAAS API with a web app that is served over https.

At the moment, the existing workarounds are to A) serve the web app over http, or B) serve the web app over https, and disable content security for the site in the browser.

Cheers,
Nicholas

**Comment by NathanQ** [comment]
Hi Nicholas,

Great question. At this time, we're not planning to serve the api over https. If we do, we would want to support both protocols as to not disrupt those who are already utilizing the api. Also, the cost of setting up an ssl certificate (though not much, but someone has to pay and do the work) comes into play. More workaround possibilities you could consider may be accessing the api server side and relay the data as your own or forking the project and running the application on your own server over https.

Take care and good luck on your project!

Nathan
