### ISSUE TITLE
MarsWeather.com

### ISSUE THREAD

**Issue by nathany** [ingenology/mars_weather_api#6]
The homepage links to http://marsweather.com/ but that domain name is currently parked.

> This domain name has been registered with Gandi.net
> It is currently being parked by the owner

**Comment by NathanQ** [comment]
@nathany unfortunately, we neglected to renew the domain and someone scooped it up then reached out to sell it back to us at a markup and we declined. 👎

**Comment by nathany** [comment]
Ugh. That's unfortunate.
