### ISSUE TITLE
Getting 502 - Bad gateway for all API requests

### ISSUE THREAD

**Issue by teldridge11** [ingenology/mars_weather_api#7]
I have been using the API successfully for a while for a site of mine, but recently noticed all my requests were getting 502's.  I did some investigating, and found that all requests to marsweather.icenology.com are returning bad gateway errors.  Something is badly broken here.

The first example from the site:

```
curl -X GET http://marsweather.ingenology.com/v1/latest/
```

Returns a 502.

**Comment by nathany** [comment]
Experiencing the same issue here (11 days later) even accessing the web site http://marsweather.ingenology.com/.

**Comment by odivalq** [comment]
Same here. It's not working anymore. What gives?

**Comment by nathany** [comment]
Looks like it's back up. Thanks!

**Comment by NathanQ** [comment]
The disk space was full b/c the nginx access log has been written to and needs to be rotated. Fixed for now. Raising issue if anyone would like to tackle this from happening again.
